name: Run Test

on: ["push"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - run: python3 -m pip install meson
      - run: meson setup build
      - run: meson compile -C build
